# Generated by Django 4.2.13 on 2024-07-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_todoitem_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('item_weight', models.FloatField()),
                ('shop_vendor', models.CharField(max_length=200)),
                ('rarity', models.CharField(max_length=200)),
            ],
        ),
    ]
