# Generated by Django 4.2.13 on 2024-07-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_weight',
            field=models.CharField(max_length=200),
        ),
    ]
