# Generated by Django 4.2.13 on 2024-08-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_alter_item_item_weight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='Dnditem',
        ),
    ]
